### ISSUE TITLE
Print processor information

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/deflatebench#11]
It would be good if the script printed the CPU information automatically. 

I've thought about using `platform.processor()` in python but not sure if it is cross-platform. On Windows, it outputs: `Intel64 Family 6 Model 140 Stepping 1, GenuineIntel`.

**Comment by Dead2** [comment]
Python 2.7 and 3.6 on EL7:
```
>>> import platform
>>> platform.processor()
'x86_64'
```
Not very useful on Linux unfortunately, but there are ways to get it. I can't look at it now, but maybe at a later opportunity.
